name: Deploy Docker to Azure (Publish Profile)

on:
  push:
    branches:
      - feature/deploy
  workflow_dispatch:

env:
  ACR_NAME: team4muluckacr
  IMAGE_NAME: team4muluck-app
  APP_SERVICE_NAME: team4muluck-docker-final

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. 소스 가져오기
      - name: Checkout Source
        uses: actions/checkout@v4

      # 2. 자바 설정
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'microsoft'

      # 3. application.yml 생성
      - name: Create application.yml
        run: |
          echo "${{ secrets.APPLICATION_YML_SECRET }}" | base64 --decode > ./application.yml

      # 4. Gradle 빌드
      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew bootJar -x test

      # 5. ACR 로그인 (Admin 계정 사용)
      - name: Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_NAME }}.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # 6. 도커 빌드 & 푸시
      - name: Build and Push Docker Image
        run: |
          docker build . -t ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
          docker build . -t ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:latest
          docker push ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
          docker push ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:latest

      # 7. 배포
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.APP_SERVICE_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: '${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}'